# Generated by Django 3.2.7 on 2021-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_actor', models.CharField(max_length=200)),
                ('movie_general', models.CharField(max_length=300)),
                ('movie_translator', models.CharField(max_length=200)),
                ('movie_cost', models.CharField(max_length=300)),
                ('movie_status1', models.CharField(choices=[('New', 'New'), ('Featured', 'Featured')], max_length=300)),
                ('movie_status2', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=200)),
                ('movie_release_date', models.DateField(auto_now_add=True)),
                ('movie_image', models.ImageField(upload_to='')),
                ('movie_video', models.CharField(max_length=200)),
            ],
        ),
    ]
