# Generated by Django 3.2.7 on 2021-10-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_carousel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
