# Generated by Django 3.2.7 on 2021-10-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_movies_movie_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
