# Generated by Django 3.2.7 on 2021-10-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='serie_image',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
    ]
