# Generated by Django 3.2.7 on 2021-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20211011_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='serie_image',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
