# Generated by Django 3.2.7 on 2021-10-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_series_serie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='serie_episode',
        ),
        migrations.RemoveField(
            model_name='series',
            name='serie_season',
        ),
        migrations.RemoveField(
            model_name='series',
            name='serie_video',
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('episode_video', models.CharField(max_length=200)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.season')),
            ],
        ),
    ]
