# Generated by Django 3.2.8 on 2021-10-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
