# Generated by Django 3.2.9 on 2021-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_status1',
            field=models.CharField(choices=[('New', 'New'), ('Featured', 'Featured')], default='New', max_length=300),
        ),
    ]
